export const TIME_TO_GET_TOKEN_BEFORE_START_IN_SECONDS = 60 * 60; // 1h
export const TIME_DIFF_BETWEEN_NOW_AND_END_DATE_FOR_SUBMISSION = 5; // 5s
// export const TIME_GAP_FOR_SUBMISSION = 60 * 30; // 30min
export const TIME_GAP_FOR_SUBMISSION = 10; // 10sec
