version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_elearning
    env_file:
      - ./.env.redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: ["redis-server"]

volumes:
  redis_data:
